<?php

namespace SocialBundle\Repository;

/**
 * ActualityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActualityRepository extends \Doctrine\ORM\EntityRepository
{
}
